package com.sdut.trade.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sdut.trade.entity.BankInfo;
import com.sdut.trade.entity.BankInfoExample;

public interface BankInfoMapper {
    long countByExample(BankInfoExample example);

    int deleteByExample(BankInfoExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(BankInfo record);

    int insertSelective(BankInfo record);

    List<BankInfo> selectByExample(BankInfoExample example);

    BankInfo selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") BankInfo record, @Param("example") BankInfoExample example);

    int updateByExample(@Param("record") BankInfo record, @Param("example") BankInfoExample example);

    int updateByPrimaryKeySelective(BankInfo record);

    int updateByPrimaryKey(BankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<BankInfo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<BankInfo> list, @Param("selective") BankInfo.Column... selective);
}