package com.sdut.trade.mapper;

import com.sdut.trade.entity.CheckInfo;
import com.sdut.trade.entity.CheckInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckInfoMapper {
    long countByExample(CheckInfoExample example);

    int deleteByExample(CheckInfoExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CheckInfo record);

    int insertSelective(CheckInfo record);

    List<CheckInfo> selectByExample(CheckInfoExample example);

    CheckInfo selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") CheckInfo record, @Param("example") CheckInfoExample example);

    int updateByExample(@Param("record") CheckInfo record, @Param("example") CheckInfoExample example);

    int updateByPrimaryKeySelective(CheckInfo record);

    int updateByPrimaryKey(CheckInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<CheckInfo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<CheckInfo> list, @Param("selective") CheckInfo.Column ... selective);
}