package com.sdut.trade.mapper;

import com.sdut.trade.entity.CheckDetail;
import com.sdut.trade.entity.CheckDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckDetailMapper {
    long countByExample(CheckDetailExample example);

    int deleteByExample(CheckDetailExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CheckDetail record);

    int insertSelective(CheckDetail record);

    List<CheckDetail> selectByExample(CheckDetailExample example);

    CheckDetail selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") CheckDetail record, @Param("example") CheckDetailExample example);

    int updateByExample(@Param("record") CheckDetail record, @Param("example") CheckDetailExample example);

    int updateByPrimaryKeySelective(CheckDetail record);

    int updateByPrimaryKey(CheckDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<CheckDetail> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<CheckDetail> list, @Param("selective") CheckDetail.Column ... selective);
}