package com.sdut.trade.mapper;

import com.sdut.trade.entity.InvoiceDetail;
import com.sdut.trade.entity.InvoiceDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvoiceDetailMapper {
    long countByExample(InvoiceDetailExample example);

    int deleteByExample(InvoiceDetailExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(InvoiceDetail record);

    int insertSelective(InvoiceDetail record);

    List<InvoiceDetail> selectByExample(InvoiceDetailExample example);

    InvoiceDetail selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") InvoiceDetail record, @Param("example") InvoiceDetailExample example);

    int updateByExample(@Param("record") InvoiceDetail record, @Param("example") InvoiceDetailExample example);

    int updateByPrimaryKeySelective(InvoiceDetail record);

    int updateByPrimaryKey(InvoiceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<InvoiceDetail> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<InvoiceDetail> list, @Param("selective") InvoiceDetail.Column ... selective);
}