package com.sdut.trade.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sdut.trade.entity.LogisticsCompanyInfo;
import com.sdut.trade.entity.LogisticsCompanyInfoExample;

public interface LogisticsCompanyInfoMapper {
    long countByExample(LogisticsCompanyInfoExample example);

    int deleteByExample(LogisticsCompanyInfoExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(LogisticsCompanyInfo record);

    int insertSelective(LogisticsCompanyInfo record);

    List<LogisticsCompanyInfo> selectByExample(LogisticsCompanyInfoExample example);

    LogisticsCompanyInfo selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") LogisticsCompanyInfo record,
                                 @Param("example") LogisticsCompanyInfoExample example);

    int updateByExample(@Param("record") LogisticsCompanyInfo record,
                        @Param("example") LogisticsCompanyInfoExample example);

    int updateByPrimaryKeySelective(LogisticsCompanyInfo record);

    int updateByPrimaryKey(LogisticsCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_company_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<LogisticsCompanyInfo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_company_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<LogisticsCompanyInfo> list,
                             @Param("selective") LogisticsCompanyInfo.Column... selective);
}