package com.sdut.trade.mapper;

import com.sdut.trade.entity.LogisticsDetail;
import com.sdut.trade.entity.LogisticsDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogisticsDetailMapper {
    long countByExample(LogisticsDetailExample example);

    int deleteByExample(LogisticsDetailExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(LogisticsDetail record);

    int insertSelective(LogisticsDetail record);

    List<LogisticsDetail> selectByExample(LogisticsDetailExample example);

    LogisticsDetail selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") LogisticsDetail record, @Param("example") LogisticsDetailExample example);

    int updateByExample(@Param("record") LogisticsDetail record, @Param("example") LogisticsDetailExample example);

    int updateByPrimaryKeySelective(LogisticsDetail record);

    int updateByPrimaryKey(LogisticsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<LogisticsDetail> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<LogisticsDetail> list, @Param("selective") LogisticsDetail.Column ... selective);
}