package com.sdut.trade.mapper;

import com.sdut.trade.entity.TermsRecord;
import com.sdut.trade.entity.TermsRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TermsRecordMapper {
    long countByExample(TermsRecordExample example);

    int deleteByExample(TermsRecordExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TermsRecord record);

    int insertSelective(TermsRecord record);

    List<TermsRecord> selectByExample(TermsRecordExample example);

    TermsRecord selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") TermsRecord record, @Param("example") TermsRecordExample example);

    int updateByExample(@Param("record") TermsRecord record, @Param("example") TermsRecordExample example);

    int updateByPrimaryKeySelective(TermsRecord record);

    int updateByPrimaryKey(TermsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<TermsRecord> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<TermsRecord> list, @Param("selective") TermsRecord.Column ... selective);
}