package com.sdut.trade.mapper;

import com.sdut.trade.entity.TransportCompanyInfo;
import com.sdut.trade.entity.TransportCompanyInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransportCompanyInfoMapper {
    long countByExample(TransportCompanyInfoExample example);

    int deleteByExample(TransportCompanyInfoExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TransportCompanyInfo record);

    int insertSelective(TransportCompanyInfo record);

    List<TransportCompanyInfo> selectByExample(TransportCompanyInfoExample example);

    TransportCompanyInfo selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") TransportCompanyInfo record, @Param("example") TransportCompanyInfoExample example);

    int updateByExample(@Param("record") TransportCompanyInfo record, @Param("example") TransportCompanyInfoExample example);

    int updateByPrimaryKeySelective(TransportCompanyInfo record);

    int updateByPrimaryKey(TransportCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_company_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<TransportCompanyInfo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_company_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<TransportCompanyInfo> list, @Param("selective") TransportCompanyInfo.Column ... selective);
}