package com.sdut.trade.entity;

import java.io.Serializable;
import java.util.Date;

public class DealDetail implements Serializable {
    private Integer id;

    private Date date;

    private Integer amount;

    private Integer type;

    private Integer way;

    private String wechatPayAccount;

    private String wechatReceiveAccount;

    private Long bankPayAccount;

    private Long bankReceiveAccount;

    private String bankName;

    private Long checkNumber;

    private String checkPayPeople;

    private String checkReceivePeople;

    private Date checkDate;

    private Date checkDeadline;

    private String remark;

    private Date createDate;

    private Date deleteDate;

    private Boolean enable;

    private Date updateDate;

    private String company;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getWay() {
        return way;
    }

    public void setWay(Integer way) {
        this.way = way;
    }

    public String getWechatPayAccount() {
        return wechatPayAccount;
    }

    public void setWechatPayAccount(String wechatPayAccount) {
        this.wechatPayAccount = wechatPayAccount == null ? null : wechatPayAccount.trim();
    }

    public String getWechatReceiveAccount() {
        return wechatReceiveAccount;
    }

    public void setWechatReceiveAccount(String wechatReceiveAccount) {
        this.wechatReceiveAccount = wechatReceiveAccount == null ? null : wechatReceiveAccount.trim();
    }

    public Long getBankPayAccount() {
        return bankPayAccount;
    }

    public void setBankPayAccount(Long bankPayAccount) {
        this.bankPayAccount = bankPayAccount;
    }

    public Long getBankReceiveAccount() {
        return bankReceiveAccount;
    }

    public void setBankReceiveAccount(Long bankReceiveAccount) {
        this.bankReceiveAccount = bankReceiveAccount;
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    public Long getCheckNumber() {
        return checkNumber;
    }

    public void setCheckNumber(Long checkNumber) {
        this.checkNumber = checkNumber;
    }

    public String getCheckPayPeople() {
        return checkPayPeople;
    }

    public void setCheckPayPeople(String checkPayPeople) {
        this.checkPayPeople = checkPayPeople == null ? null : checkPayPeople.trim();
    }

    public String getCheckReceivePeople() {
        return checkReceivePeople;
    }

    public void setCheckReceivePeople(String checkReceivePeople) {
        this.checkReceivePeople = checkReceivePeople == null ? null : checkReceivePeople.trim();
    }

    public Date getCheckDate() {
        return checkDate;
    }

    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    public Date getCheckDeadline() {
        return checkDeadline;
    }

    public void setCheckDeadline(Date checkDeadline) {
        this.checkDeadline = checkDeadline;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getDeleteDate() {
        return deleteDate;
    }

    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }

    public Boolean getEnable() {
        return enable;
    }

    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table deal_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        date("date"),
        amount("amount"),
        type("type"),
        way("way"),
        wechatPayAccount("wechat_pay_account"),
        wechatReceiveAccount("wechat_receive_account"),
        bankPayAccount("bank_pay_account"),
        bankReceiveAccount("bank_receive_account"),
        bankName("bank_name"),
        checkNumber("check_number"),
        checkPayPeople("check_pay_people"),
        checkReceivePeople("check_receive_people"),
        checkDate("check_date"),
        checkDeadline("check_deadline"),
        remark("remark"),
        createDate("create_date"),
        deleteDate("delete_date"),
        enable("enable"),
        updateDate("update_date"),
        company("company");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table deal_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table deal_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table deal_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table deal_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table deal_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table deal_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}